<?php

    /**
    *
    * Generated by DezDevTools @ 2016-03-14 20:26:25
    *
    * @author Ivan Gontarenko
    * @licence MIT
    *
    */

    namespace SiteDezz\Model\Entity;

    use SiteDezz\Model\Entity\GeneratedEntity\Entity_1e84be86c98ed15b6b4a21fa7f0c4586;

    class ArticleTagRef extends Entity_1e84be86c98ed15b6b4a21fa7f0c4586
    {

        /**
         * @return Articles
         * @throws \Dez\ORM\Exception
         */
        public function articles()
        {
            return $this->hasOne(Articles::class, 'id', 'article_id');
        }

        /**
         * @return ArticleTags
         * @throws \Dez\ORM\Exception
         */
        public function tag()
        {
            return $this->hasOne(ArticleTags::class, 'id', 'tag_id');
        }

    }