<?php

    /**
    *
    * Generated by DezDevTools @ 2016-03-13 17:41:51
    *
    * @author Ivan Gontarenko
    * @licence MIT
    *
    */

    namespace SiteDezz\Model\Entity;

    use SiteDezz\Model\Entity\GeneratedEntity\Entity_6694884f727937d6fa8f476277719566;

    class ArticleCategories extends Entity_6694884f727937d6fa8f476277719566
    {

        public static function tree()
        {
            $treeArray = [];
            $references = [];

            /** @var ArticleCategories $item */
            foreach(static::all() as $item) {
                $referenceItem = &$references[$item->id()];

                $referenceItem['id'] = $item->id();
                $referenceItem['parent_id'] = $item->getParentId();
                $referenceItem['title'] = $item->getTitle();
                $referenceItem['slug'] = $item->getSlug();

                if($item->getParentId() == 0) {
                    $treeArray[$item->id()] = &$referenceItem;
                } else {
                    $references[$item->getParentId()]['children'][$item->id()] = &$referenceItem;
                }
            }

            return $treeArray;
        }

    }