<?php

    /**
    *
    * Generated by DezDevTools @ 2016-03-13 17:35:06
    *
    * @author Ivan Gontarenko
    * @licence MIT
    *
    */

    namespace SiteDezz\Model\Entity;

    use Dez\ORM\Collection\ModelCollection;
    use Dez\ORM\Model\QueryBuilder;
    use SiteDezz\Model\Entity\GeneratedEntity\Entity_dba5d91846ce1a5e63734dfcbcb481cb;

    class Articles extends Entity_dba5d91846ce1a5e63734dfcbcb481cb
    {

        /**
         * @return ModelCollection
         * @throws \Dez\ORM\Exception
         */
        public function tags()
        {
            return $this->hasMany(ArticleTags::class, 'id', 'article_id');
        }

        /**
         * @return ArticleCategories
         * @throws \Dez\ORM\Exception
         */
        public function category()
        {
            return $this->hasOne(ArticleCategories::class, 'id', 'category_id');
        }

        /**
         * @return QueryBuilder
         */
        public static function popular()
        {
            return static::query()->order('views', 'desc');
        }

        public function createTags($tags)
        {
            ArticleTags::query()->where('article_id', $this->id())->delete();

            $tags = array_map(function($tag){
                return trim($tag);
            }, explode(',', $tags));

            die(var_dump($tags));
        }

    }