<?php

    /**
    *
    * Generated by DezDevTools @ 2016-03-13 17:41:17
    *
    * @author Ivan Gontarenko
    * @licence MIT
    *
    */

    namespace SiteDezz\Model\Entity;

    use SiteDezz\Model\Entity\GeneratedEntity\Entity_5c7de2a4809be9f904c0994c730c58df;

    class ArticleTags extends Entity_5c7de2a4809be9f904c0994c730c58df
    {

        /**
         * @return \Dez\ORM\Collection\ModelCollection
         * @throws \Dez\ORM\Exception
         */
        public function refs()
        {
            return $this->hasMany(ArticleTagRef::class, 'tag_id');
        }

    }