<?php

    /**
    *
    * Generated by DezDevTools @ 2016-03-16 17:55:02
    *
    * @author Ivan Gontarenko
    * @licence MIT
    *
    */

    namespace SiteDezz\Model\Entity;

    use SiteDezz\Model\Entity\GeneratedEntity\Entity_ca29ae7490314d52bb744232e6a0b7f8;

    class BinSources extends Entity_ca29ae7490314d52bb744232e6a0b7f8
    {

        /**
         * @return LatinWords
         * @throws \Dez\ORM\Exception
         */
        public function slug()
        {
            return $this->hasOne(LatinWords::class, 'id', 'slug_key');
        }

        /**
         * @return LatinWords
         */
        public static function randomSlug()
        {
            do{
                $latin = LatinWords::one(rand(1, LatinWords::MAX_ID));
                $bin = static::one($latin->id());
            } while($bin->exists());

            return $latin;
        }

        public static function languages()
        {
            return [
                'PHP' => 'php',
                'Java' => 'java',
                'C++' => 'cpp',
                'Python' => 'python',
                'Ruby' => 'ruby',
                'JavaScript' => 'js',
                'HTML' => 'html',
            ];
        }

    }