<?php

    /**
    *
    * Generated by DezDevTools @ 2016-03-16 18:13:31
    *
    * @author Ivan Gontarenko
    * @licence MIT
    *
    */

    namespace SiteDezz\Model\Entity;

    use SiteDezz\Model\Entity\GeneratedEntity\Entity_eb54071c4feeb0046e14f4d58c9924c6;

    class LatinWords extends Entity_eb54071c4feeb0046e14f4d58c9924c6
    {

        const MAX_ID = 78564;

        /**
         * @return BinSources
         * @throws \Dez\ORM\Exception
         */
        public function bin()
        {
            return $this->hasOne(BinSources::class, 'slug_key');
        }

    }