<?php

    /**
     *
     * Generated by DezDevTools @ 2016-03-13 17:41:58
     *
     * @author Ivan Gontarenko
     * @licence MIT
     *
    */

    namespace SiteDezz\Model\Entity\GeneratedEntity;

    use Dez\ORM\Model\Table as OrmEntity;

    class Entity_6694884f727937d6fa8f476277719566 extends OrmEntity {

        static protected $table     = 'article_categories';
        
        /**
         * @return mixed
         */
        public function getParentId() {
            return $this->get( 'parent_id' );
        }

        /**
         * @param mixed $parent_id
         * @return $this
         */
        public function setParentId( $parent_id ) {
            $this->set( 'parent_id', $parent_id );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getTitle() {
            return $this->get( 'title' );
        }

        /**
         * @param mixed $title
         * @return $this
         */
        public function setTitle( $title ) {
            $this->set( 'title', $title );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getSlug() {
            return $this->get( 'slug' );
        }

        /**
         * @param mixed $slug
         * @return $this
         */
        public function setSlug( $slug ) {
            $this->set( 'slug', $slug );
            return $this;
        }
        
    }