<?php

    /**
     *
     * Generated by DezDevTools @ 2016-03-14 20:27:07
     *
     * @author Ivan Gontarenko
     * @licence MIT
     *
    */

    namespace SiteDezz\Model\Entity\GeneratedEntity;

    use Dez\ORM\Model\Table as OrmEntity;

    class Entity_1e84be86c98ed15b6b4a21fa7f0c4586 extends OrmEntity {

        static protected $table     = 'article_tag_ref';
        
        /**
         * @return mixed
         */
        public function getTagId() {
            return $this->get( 'tag_id' );
        }

        /**
         * @param mixed $tag_id
         * @return $this
         */
        public function setTagId( $tag_id ) {
            $this->set( 'tag_id', $tag_id );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getArticleId() {
            return $this->get( 'article_id' );
        }

        /**
         * @param mixed $article_id
         * @return $this
         */
        public function setArticleId( $article_id ) {
            $this->set( 'article_id', $article_id );
            return $this;
        }
        
    }