<?php

    /**
     *
     * Generated by DezDevTools @ 2016-03-16 17:55:02
     *
     * @author Ivan Gontarenko
     * @licence MIT
     *
    */

    namespace SiteDezz\Model\Entity\GeneratedEntity;

    use Dez\ORM\Model\Table as OrmEntity;

    class Entity_ca29ae7490314d52bb744232e6a0b7f8 extends OrmEntity {

        static protected $table     = 'bin_sources';
        
        /**
         * @return mixed
         */
        public function getSlugKey() {
            return $this->get( 'slug_key' );
        }

        /**
         * @param mixed $slug_key
         * @return $this
         */
        public function setSlugKey( $slug_key ) {
            $this->set( 'slug_key', $slug_key );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getTitle() {
            return $this->get( 'title' );
        }

        /**
         * @param mixed $title
         * @return $this
         */
        public function setTitle( $title ) {
            $this->set( 'title', $title );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getLanguage() {
            return $this->get( 'language' );
        }

        /**
         * @param mixed $language
         * @return $this
         */
        public function setLanguage( $language ) {
            $this->set( 'language', $language );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getSourceCode() {
            return $this->get( 'source_code' );
        }

        /**
         * @param mixed $source_code
         * @return $this
         */
        public function setSourceCode( $source_code ) {
            $this->set( 'source_code', $source_code );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getCreatedAt() {
            return $this->get( 'created_at' );
        }

        /**
         * @param mixed $created_at
         * @return $this
         */
        public function setCreatedAt( $created_at ) {
            $this->set( 'created_at', $created_at );
            return $this;
        }
        
    }