<?php

    /**
     *
     * Generated by DezDevTools @ 2016-03-16 18:13:31
     *
     * @author Ivan Gontarenko
     * @licence MIT
     *
    */

    namespace SiteDezz\Model\Entity\GeneratedEntity;

    use Dez\ORM\Model\Table as OrmEntity;

    class Entity_eb54071c4feeb0046e14f4d58c9924c6 extends OrmEntity {

        static protected $table     = 'latin_words';
        
        /**
         * @return mixed
         */
        public function getWord() {
            return $this->get( 'word' );
        }

        /**
         * @param mixed $word
         * @return $this
         */
        public function setWord( $word ) {
            $this->set( 'word', $word );
            return $this;
        }
        
    }