<?php

    /**
     *
     * Generated by DezDevTools @ 2016-03-13 17:41:17
     *
     * @author Ivan Gontarenko
     * @licence MIT
     *
    */

    namespace SiteDezz\Model\Entity\GeneratedEntity;

    use Dez\ORM\Model\Table as OrmEntity;

    class Entity_5c7de2a4809be9f904c0994c730c58df extends OrmEntity {

        static protected $table     = 'article_tags';
        
        /**
         * @return mixed
         */
        public function getArticleId() {
            return $this->get( 'article_id' );
        }

        /**
         * @param mixed $article_id
         * @return $this
         */
        public function setArticleId( $article_id ) {
            $this->set( 'article_id', $article_id );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getTag() {
            return $this->get( 'tag' );
        }

        /**
         * @param mixed $tag
         * @return $this
         */
        public function setTag( $tag ) {
            $this->set( 'tag', $tag );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getName() {
            return $this->get( 'name' );
        }

        /**
         * @param mixed $name
         * @return $this
         */
        public function setName( $name ) {
            $this->set( 'name', $name );
            return $this;
        }
        
    }